import Head from "next/head";
import { createClient } from "next-sanity";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";
import NavBar from "../components/NavBar/nav-bar";

const inter = Inter({ subsets: ["latin"] });

const client = createClient({
  projectId: "tjqwyy5h",
  dataset: "production",
  apiVersion: "2023-01-07",
  useCdn: false,
});

export default function Home() {
  const { data: session } = useSession();
  const { status } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar />
      </main>
    </>
  );
}
