import Head from "next/head";
import Image from "next/image";
import { createClient } from "next-sanity";
import { FormEnum } from "../components/forms/form-enum";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Form from "../components/forms/form";

const inter = Inter({ subsets: ["latin"] });

const client = createClient({
  projectId: "tjqwyy5h",
  dataset: "production",
  apiVersion: "2023-01-07",
  useCdn: false,
});

export default function Home({ movie }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Form type={FormEnum.SIGNIN}></Form>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const movie = await client.fetch(`*[_type == "movie"]`);
  return {
    props: {
      movie,
    },
  };
};
