import Head from "next/head";
import Image from "next/image";
import { createClient } from "next-sanity";
import { FormEnum } from "../components/forms/form-enum";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Form from "../components/forms/form";
import { signOut, useSession } from "next-auth/react";
import { Button } from "../components/forms/form-style";
import { useRouter } from "next/router";
import { useEffect } from "react";
import NavBar from "../components/NavBar/nav-bar";
import styled from "styled-components";
import {
  SearchInput,
} from "../components/NavBar/nav-bar.styles";

const Container = styled.div`
  width: 100vw;
  min-height: 100vh;
  max-height: auto;
  padding: 100px 0
`;

export const SearchInputWrapper = styled.div`
  display: flex;
  justify-content: flex-start;
  align-items: center;
`;

export default function Home() {
  const { data: session } = useSession();
  const { status } = useSession();

  return (
    <>
      <Head>
        <title>Search page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar />
        <Container>
          <SearchInputWrapper>
            <Image
              alt="search-icon"
              src={"/assets/icon-search.svg"}
              width={24}
              height={24}
            />
            <SearchInput placeholder="Search for movies or TV series" />
          </SearchInputWrapper>
        </Container>
      </main>
    </>
  );
}
