import Head from "next/head";
import styles from "../styles/Home.module.css";
import { signOut, useSession } from "next-auth/react";
import { useEffect } from "react";
import NavBar from "../components/nav-bar/nav-bar";
import { GetServerSideProps } from "next";
import { client } from "../utils/image-loader";
import IMediaItem from "../components/cards/media-item";
import Grid from "../components/grid/grid";
import { CardArea, GridArea } from "../styles/common";

interface MovieProps {
  shows: Array<IMediaItem>;
}

export default function Shows({ shows }: MovieProps) {
  const { data: session } = useSession();
  const { status } = useSession();



  return (
    <>
      <Head>
        <title>Shows</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar />
        <GridArea>{shows && <Grid items={shows} heading={"TV Series"} />}</GridArea>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const shows = await client.fetch(`*[category == "TV Series"]`);

  if (!shows) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      shows,
    },
  };
};
