import Head from "next/head";
import React from "react";
import Form from "../components/forms/form";
import styles from "../styles/Home.module.css";
import { FormEnum } from "../components/forms/form-enum";

const SignIn = () => {
  return (
    <>
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Form type={FormEnum.SIGNIN}></Form>
      </main>
    </>
  );
};

export default SignIn;
