import Head from "next/head";
import React from "react";
import Form from "../components/forms/form";
import styles from "../styles/Home.module.css";
import { FormEnum } from "../components/forms/form-enum";

const SignUp = () => {
  return (
    <>
      <Head>
        <title>Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Form type={FormEnum.SIGNUP}></Form>
      </main>
    </>
  );
};

export default SignUp;
