import Head from "next/head";
import React, { useEffect } from "react";
import Form from "../components/forms/form";
import styles from "../styles/Home.module.css";
import { FormEnum } from "../components/forms/form-enum";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";

const SignIn = () => {
  const session = useSession()
  const router = useRouter()

  useEffect(() => {
    if (session.status === "unauthenticated") {
      setTimeout(() => {
        router.push("/sign-in");
      }, 3000);
    } 
    else if(session.status === "authenticated") {
      router.push("/home");
    }
  }, [session]);
  
  return (
    <>
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Form></Form>
      </main>
    </>
  );
};

export default SignIn;
